---
deployment:
  tasks:
    - /bin/mkdir /home/andresc/www/PayPal
    - /bin/chmod 755 /home/andresc/www/PayPal
    - export DEPLOYPATH=/home/andresc/www/PayPal
    - /bin/cp -R cancelled.php db/ $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    
