---
deployment:
  tasks:
    - /bin/mkdir /home/andresc/www/PayPal
    - /bin/chmod 755 /home/andresc/www/PayPal
    - export DEPLOYPATH=/home/andresc/www/PayPal
    - /bin/rm -rf $DEPLOYPATH/* $DEPLOYPATH/.*
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    
