---
deployment:
  tasks:
    - export DEPLOYPATH=/home/andresc/www/PayPal
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    
